# Generated by Django 4.2.7 on 2026-07-31 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('follow', 'Follow'), ('comment', 'Comment'), ('clap', 'Clap'), ('bookmark', 'Bookmark'), ('mention', 'Mention')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=20)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
