# Generated by Django 4.2.7 on 2026-08-20 12:38

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(default='#1F4E4A', max_length=7, validators=[core.utils.validate_hex_color]),
        ),
    ]
