const baseURL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api/v1/';

const normalizedBase = baseURL.endsWith('/') ? baseURL : baseURL + '/';

export const endpoints = {
  register: `${normalizedBase}auth/register/`,
  login: `${normalizedBase}auth/login/`,
  refresh: `${normalizedBase}auth/refresh/`,
  verify: `${normalizedBase}auth/verify/`,
  me: `${normalizedBase}auth/me/`,
  logout: `${normalizedBase}auth/logout/`,
  users: (handle) => `${normalizedBase}users/${handle}/`,
  userStories: (handle) => `${normalizedBase}users/${handle}/stories/`,
  userFollowers: (handle) => `${normalizedBase}users/${handle}/followers/`,
  userFollowing: (handle) => `${normalizedBase}users/${handle}/following/`,
  userFollow: (handle) => `${normalizedBase}users/${handle}/follow/`,
  userUpdate: (handle) => `${normalizedBase}users/${handle}/update/`,
  userAvatar: (handle) => `${normalizedBase}users/${handle}/avatar/`,
  articles: `${normalizedBase}articles/`,
  article: (id) => `${normalizedBase}articles/${id}/`,
  clap: (id) => `${normalizedBase}articles/${id}/clap/`,
  featured: `${normalizedBase}articles/featured/`,
  trending: `${normalizedBase}articles/trending/`,
  comments: `${normalizedBase}comments/`,
  commentList: (articleId) => `${normalizedBase}comments/?article=${articleId}`,
  bookmarks: `${normalizedBase}bookmarks/`,
  bookmark: (articleId) => `${normalizedBase}bookmarks/${articleId}/`,
  notifications: `${normalizedBase}notifications/`,
  notificationRead: (id) => `${normalizedBase}notifications/${id}/read/`,
  notificationReadAll: `${normalizedBase}notifications/read_all/`,
  history: `${normalizedBase}history/`,
  reports: `${normalizedBase}reports/`,
  tags: `${normalizedBase}articles/tags/`,
  tagArticles: (slug) => `${normalizedBase}articles/?tags__slug=${slug}`,
  chatbot: `${normalizedBase}rag/chat/stream/`,
  chatbotActions: `${normalizedBase}rag/chat/`,
  chatbotHealth: `${normalizedBase}rag/health/`,
  newsletterSubscribe: `${normalizedBase}newsletter/subscribe/`,
  newsletterConfirm: (token) => `${normalizedBase}newsletter/confirm/${token}/`,
  newsletterUnsubscribe: `${normalizedBase}newsletter/unsubscribe/`,
  newsletterStatus: (email) => `${normalizedBase}newsletter/status/?email=${encodeURIComponent(email)}`,
  newsletterStats: `${normalizedBase}newsletter/stats/`,
};

export default endpoints;
