name: Deploy Django Backend to Azure

on:
  push:
    paths:
      - 'blog_backend/**'
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: medium-blog-backend-dsdffvf9hugchhfg
  AZURE_WEBAPP_PACKAGE_PATH: './blog_backend'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: |
          cd blog_backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}